# Generated by Django 3.0.2 on 2020-01-31 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Motorista',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100)),
                ('cpf', models.CharField(max_length=11)),
                ('telefone', models.CharField(max_length=20)),
                ('sexo', models.CharField(choices=[('feminino', 'Feminino'), ('masculino', 'Masculino')], max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modelo', models.CharField(max_length=50)),
                ('placa', models.CharField(max_length=8)),
                ('ano', models.CharField(max_length=4)),
                ('estado', models.CharField(choices=[('disponível', 'Disponível'), ('manutenção', 'Manutenção')], max_length=20)),
                ('foto_veiculo', models.ImageField(upload_to='images')),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data_inicio', models.DateTimeField()),
                ('data_final', models.DateTimeField()),
                ('estado_reserva', models.CharField(max_length=50)),
                ('motorista', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Motorista')),
                ('veiculo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='app.Veiculo')),
            ],
        ),
    ]
